{{- range $serviceName, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.port }}
  selector:
    app: {{ $serviceName }}
---
{{- end }}