apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: rtsp
spec:
  ports:
    - port: 1883
      targetPort: 1883
  selector:
    app: mqtt
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: rtsp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
        - name: mqtt
          image: eclipse-mosquitto:2.0.15
          ports:
            - containerPort: 1883
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"